package com.example.demo.application.familyManager.dao.dto;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.example.demo.system.database.dynamoDB.service.impl.AmazonDynamoDbConverterConfig.JsonConverter;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 
 * @DynamoDBTable(tableName = "Comment"): 해당 클래스를 엔티티로 설정합니다.
 * @DynamoDBHashKey(attributeName = "id"): 해당 필드를 HashKey로 설정합니다.
 * @DynamoDBAutoGeneratedKey: 자동으로 Key를 생성합니다. UUID를 활용합니다.
 * @DynamoDBAttribute: 해당 필드를 Attribute로 설정합니다.
 * @DynamoDBTyped(DynamoDBAttributeType.BOOL): 해당 타입을 DynamoDB의 BOOL타입으로 설정합니다.
 * @DynamoDBIndexHashKey(globalSecondaryIndexName = "byMentionId"): byMentionId라는 이름의 global secondary index의 HashKey를 설정합니다.
 * @DynamoDBIndexRangeKey(globalSecondaryIndexName = "byMentionId"): byMentionId라는 이름의 global secondary index의 RangeKey를 설정합니다.
 * 
 * @author HoYoung.Rhee
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "family")
public class FamilyDto {

	@DynamoDBHashKey(attributeName = "familyId")
	private String familyId;
	
	@DynamoDBAttribute(attributeName = "familyName")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byFamilyName")
	private String familyName;
	
//	@DynamoDBAttribute
//	@DynamoDBTyped(DynamoDBAttributeType.M)
//	private Map<String, String> remark;
	
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = JsonConverter.class)
	private Map<String, Object> remark;
}