server:
  port: 12794
  
spring:
  main:
    allow-bean-definition-overriding: true
  
dynamo:
  datasource:
    url: http://192.168.0.10:8000

cloud:  aws:    credentials:      access-key: 
      secret-key:     region:      static: 