server:
  port: 12794
  
spring:
  main:
    allow-bean-definition-overriding: true
  
dynamo:
  datasource:
    #url: http://192.168.0.10:8000
    url: 

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: 
      
application:
  apiService:
    dynamoTable:
      category:
        provisionedThroughput:
          readCapacityUnits: 10
          writeCapacityUnits: 10
      service:
        provisionedThroughput:
          readCapacityUnits: 10
          writeCapacityUnits: 10
      api:
        provisionedThroughput:
          readCapacityUnits: 10
          writeCapacityUnits: 10